# Gunakan image Python
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy file requirements dan install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy seluruh kode aplikasi ke dalam container
COPY . .

# Expose port 8080
EXPOSE 8080

# Jalankan aplikasi
CMD ["python", "app.py"]
